---
name: Trivy Full Scan

"on":
  pull_request:
    branches:
      - main

jobs:
  trivy-full-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          exit-code: 1